### ISSUE TITLE
first implementation

### ISSUE THREAD

**Issue by bunnybones1** [0xsequence/primary-drop-sale-boilerplate#2]
The user sees a template of an 1155 NFT from the project's builder
The user pays a set amount ($1)
The 1155 gets minted

**Comment by RichardIrala** [comment]
¿User pays $1 with credit card or with crypto? Edit:
Resolved: The user can pay with crypto or credit card

**Comment by RichardIrala** [comment]
Should I add information about the active chain and a switch chain to display different ERC1155 templates? Edit:
Resolved: Yes, I should add everything

**Comment by RichardIrala** [comment]
Tasks
- [x] Add Switch chain
- [x] Display active chain into UI
- [x] Add pay with crypto
- [x] Add display of an 1155 NFT from the project's builder
- [x] The NFT is minted when the user pays
- [x] Check if the user has enough money to purchase

Deleted tasks:
* The user pays 1$ to mint an NFT in his account

**Comment by RichardIrala** [comment]
> Should I add information about the active chain and a switch chain to display different ERC1155 templates?

Question resolved with James

**Comment by bunnybones1** [comment]
completed via https://github.com/0xsequence/primary-drop-sale-boilerplate/pull/5
